Add ability to open multiple files

diff --git a/rmate b/rmate
--- a/rmate
+++ b/rmate
@@ -405,28 +405,33 @@ function handle_connection {
     log "Done"
 }
 
-# connect to textmate and send command
-#
-exec 3<> "/dev/tcp/$host/$port"
+function rmate_each {
+    # connect to textmate and send command
+    #
+    exec 3<> "/dev/tcp/$host/$port"
 
-if [ $? -gt 0 ]; then
-    echo "Unable to connect to TextMate on $host:$port"
-    exit 1
-fi
+    if [ $? -gt 0 ]; then
+        echo "Unable to connect to TextMate on $host:$port"
+        exit 1
+    fi
 
-read -r server_info 0<&3
+    read -r server_info 0<&3
+    log $server_info
 
-log $server_info
+    open_file "$1"
+    [[ $? != 0 ]] && return 1
+
+    echo "." 1>&3
+
+    if [[ $nowait = true ]]; then
+        exec </dev/null >/dev/null 2>/dev/null
+        ( (handle_connection &) &)
+    else
+        handle_connection
+    fi
+}
 
 for i in "${!filepaths[@]}"; do
-    open_file "$i"
+    (rmate_each $i)
+    [[ $? = 0 ]] && new='false'
 done
-
-echo "." 1>&3
-
-if [[ $nowait = true ]]; then
-    exec </dev/null >/dev/null 2>/dev/null
-    ( (handle_connection &) &)
-else
-    handle_connection
-fi
