resolve shellcheck SC2164 by handling failed "cd"

diff --git a/rmate b/rmate
--- a/rmate
+++ b/rmate
@@ -123,14 +123,14 @@ function log {
 }
 
 function dirpath {
-    (cd `dirname $1` >/dev/null 2>/dev/null; pwd -P)
+    (cd "$(dirname "$1")" >/dev/null 2>/dev/null || { echo "unable to cd to $1 directory" 1>&2; exit; } ; pwd -P)
 }
 
 function canonicalize {
     filepath="$1"
     dir=`dirpath "$filepath"`
     if [ -L "$filepath" ]; then
-        relativepath=`cd "$dir"; readlink \`basename "$filepath"\``
+        relativepath="$(cd "$dir" || { echo "unable to cd to $dir" 1>&2; exit; } ; readlink "$(basename "$filepath")")"
         result=`dirpath "$relativepath"`/`basename "$relativepath"`
     else
         result=`basename "$filepath"`
